basePath: /
definitions:
  avito-task_internal_domain.Role:
    enum:
    - admin
    - user
    type: string
    x-enum-varnames:
    - RoleAdmin
    - RoleUser
  avito-task_internal_domain.Room:
    properties:
      createdAt:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  internal_infrastructure_http.BookingDTO:
    properties:
      createdAt:
        example: "2024-04-04T13:00:00Z"
        format: date-time
        type: string
      id:
        type: string
      slotId:
        type: string
      status:
        type: string
      userId:
        type: string
    type: object
  internal_infrastructure_http.BookingListResponse:
    properties:
      bookings:
        items:
          $ref: '#/definitions/internal_infrastructure_http.BookingDTO'
        type: array
      pagination:
        $ref: '#/definitions/internal_infrastructure_http.PaginatedBookingsResponse'
    type: object
  internal_infrastructure_http.BookingResponse:
    properties:
      booking:
        $ref: '#/definitions/internal_infrastructure_http.BookingDTO'
    type: object
  internal_infrastructure_http.CreateBookingRequest:
    properties:
      slotId:
        type: string
    type: object
  internal_infrastructure_http.CreateRoomRequest:
    properties:
      capacity:
        type: integer
      createdAt:
        example: "2024-04-04T13:00:00Z"
        type: string
      description:
        type: string
      name:
        type: string
    type: object
  internal_infrastructure_http.CreateScheduleRequest:
    properties:
      daysOfWeek:
        items:
          type: integer
        type: array
      endTime:
        example: "18:00"
        type: string
      startTime:
        example: "09:00"
        type: string
    type: object
  internal_infrastructure_http.DummyLoginRequest:
    properties:
      role:
        example: user
        type: string
    type: object
  internal_infrastructure_http.ErrorDetails:
    properties:
      code:
        type: string
      message:
        example: Detailed error message
        type: string
    type: object
  internal_infrastructure_http.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/internal_infrastructure_http.ErrorDetails'
    type: object
  internal_infrastructure_http.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  internal_infrastructure_http.PaginatedBookingsResponse:
    properties:
      page:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  internal_infrastructure_http.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      role:
        $ref: '#/definitions/avito-task_internal_domain.Role'
    type: object
  internal_infrastructure_http.RoomListResponse:
    properties:
      rooms:
        items:
          $ref: '#/definitions/avito-task_internal_domain.Room'
        type: array
    type: object
  internal_infrastructure_http.RoomResponse:
    properties:
      room:
        $ref: '#/definitions/avito-task_internal_domain.Room'
    type: object
  internal_infrastructure_http.ScheduleDTO:
    properties:
      daysOfWeek:
        items:
          type: integer
        type: array
      endTime:
        example: "2024-04-04T13:00:00Z"
        format: date-time
        type: string
      id:
        type: string
      roomId:
        type: string
      startTime:
        example: "2024-04-04T13:00:00Z"
        format: date-time
        type: string
    type: object
  internal_infrastructure_http.ScheduleResponse:
    properties:
      schedule:
        $ref: '#/definitions/internal_infrastructure_http.ScheduleDTO'
    type: object
  internal_infrastructure_http.SlotResponse:
    properties:
      end:
        example: "2024-04-04T13:00:00Z"
        format: date-time
        type: string
      id:
        type: string
      roomId:
        type: string
      start:
        example: "2024-04-04T13:00:00Z"
        format: date-time
        type: string
    type: object
  internal_infrastructure_http.SlotsListResponse:
    properties:
      slots:
        items:
          $ref: '#/definitions/internal_infrastructure_http.SlotResponse'
        type: array
    type: object
  internal_infrastructure_http.TokenResponse:
    properties:
      token:
        type: string
    type: object
  internal_infrastructure_http.UserResponse:
    properties:
      createdAt:
        example: "2024-04-04T13:00:00Z"
        format: date-time
        type: string
      email:
        type: string
      id:
        type: string
      role:
        $ref: '#/definitions/avito-task_internal_domain.Role'
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for conference room booking system.
  title: Booking Service API
  version: "1.0"
paths:
  /bookings/{bookingId}/cancel:
    post:
      description: Cancels a booking by its ID. Only the owner of the booking can
        perform this action
      parameters:
      - description: ID of the booking to cancel (UUID)
        in: path
        name: bookingId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Booking cancelled
          schema:
            $ref: '#/definitions/internal_infrastructure_http.BookingResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "404":
          description: Booking not found
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Cancel a booking
      tags:
      - Bookings
  /bookings/create:
    post:
      consumes:
      - application/json
      description: Creates a new booking for a specific slot. Only accessible by users
        with the 'user' role
      parameters:
      - description: Booking details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_infrastructure_http.CreateBookingRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Booking created successfully
          schema:
            $ref: '#/definitions/internal_infrastructure_http.BookingResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "404":
          description: Slot not found
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "409":
          description: Slot already booked
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create a booking for a slot
      tags:
      - Bookings
  /bookings/list:
    get:
      description: Returns a paginated list of all bookings in the system. Accessible
        only by users with the 'admin' role.
      parameters:
      - description: Page number (starting from 1). Default is 1
        in: query
        name: page
        type: integer
      - description: Number of items per page. Default 20, max 100
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of all bookings
          schema:
            $ref: '#/definitions/internal_infrastructure_http.PaginatedBookingsResponse'
        "400":
          description: Invalid pagination parameters
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
      security:
      - BearerAuth: []
      summary: List all bookings with pagination
      tags:
      - Bookings
  /bookings/my:
    get:
      description: Returns a list of bookings belonging to the user identified by
        the JWT token
      produces:
      - application/json
      responses:
        "200":
          description: List of future bookings
          schema:
            $ref: '#/definitions/internal_infrastructure_http.BookingListResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
      security:
      - BearerAuth: []
      summary: List bookings for the current user
      tags:
      - Bookings
  /dummyLogin:
    post:
      consumes:
      - application/json
      description: Return string JWT token by role (admin / user) with fixed UUID.
      parameters:
      - description: User role
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_infrastructure_http.DummyLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_infrastructure_http.TokenResponse'
        "400":
          description: Invalid role
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "500":
          description: Internal error
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
      summary: Get string JWT token by role
      tags:
      - Auth
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates a user by email and password, returning a JWT token
      parameters:
      - description: User credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_infrastructure_http.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully authenticated
          schema:
            $ref: '#/definitions/internal_infrastructure_http.TokenResponse'
        "401":
          description: Invalid email or password
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
      summary: User login
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: Create new user and return his data
      parameters:
      - description: Registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_infrastructure_http.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User create
          schema:
            additionalProperties:
              $ref: '#/definitions/internal_infrastructure_http.UserResponse'
            type: object
        "400":
          description: Invalid request or email already taken
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "500":
          description: Internal server data
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
      summary: User registration
      tags:
      - Auth
  /rooms/{roomId}/schedule/create:
    post:
      consumes:
      - application/json
      description: Defines the availability rules for a conference room. Can be created
        only once per room
      parameters:
      - description: Room ID (UUID)
        in: path
        name: roomId
        required: true
        type: string
      - description: Schedule definition
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_infrastructure_http.CreateScheduleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Schedule created successfully
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ScheduleResponse'
        "400":
          description: Invalid request or invalid daysOfWeek values
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "404":
          description: Room not found
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "409":
          description: 'Conflict: schedule already exists for this room'
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create room availability schedule
      tags:
      - Schedules
  /rooms/{roomId}/slots/list:
    get:
      description: Returns a list of slots that are not occupied by an active booking
        for a specific room and date
      parameters:
      - description: Room ID (UUID)
        in: path
        name: roomId
        required: true
        type: string
      - description: Date in ISO 8601 format (e.g., 2024-06-10)
        in: query
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of available slots
          schema:
            $ref: '#/definitions/internal_infrastructure_http.SlotsListResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "404":
          description: Room not found
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
      security:
      - BearerAuth: []
      summary: List available slots for a room by date
      tags:
      - Slots
  /rooms/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Room data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_infrastructure_http.CreateRoomRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_infrastructure_http.RoomResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create room
      tags:
      - Rooms
  /rooms/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_infrastructure_http.RoomListResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_infrastructure_http.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Rooms list
      tags:
      - Rooms
swagger: "2.0"
